export const projectOne = [
  {
    id: 'a1',
    image: '/images/projectCard/oasis_spain.jpg',
    price: '725,000',
    pricePerMeter: '3,326',
    title: 'Oasis 325 Phase II',
    bed: '4',
    bathrooms: '',
    location: 'Calle Cam, del Reloj',
    floors: '5',
    floor: '',
    projectFloor: '5',
    rooms: '3',
    type: 'Apartment',
    size: '124',
    description: [
      'Oasis 325 – Phase 2 builds on the success of the original Oasis 325 project, offering apartments in Estepona. Like its predecessor, Oasis 325 – Phase 2 benefits from its prime location between Marbella and Estepona. Within just 10 minutes, you can access top golf courses, the exotic Selwo Park, numerous beach clubs, restaurants, shops, and other amenities.',
      'This phase includes 88 exclusive apartments in Estepona, thoughtfully designed to maximize sunlight, enhancing the Mediterranean lifestyle. The development offers a mix of 2 and 3 bedroom units, including ground-floor apartments with gardens and penthouses featuring solariums. Each apartment comes with a garage and a storage room.',
      'The interior layout is uniquely designed to create spacious living areas that merge indoor and outdoor spaces, optimizing daylight. The open-plan kitchens and living areas open onto expansive terraces, offering stunning views of the surrounding natural landscape.',
      'The apartments are constructed with high-quality materials and feature a distinctive architectural style to ensure an exceptional living experience. All units enjoy a favorable south-facing orientation.',
    ],
    amenities: [
      'Gym',
      'Bank',
      'Concierge',
      'Elevator',
      'Green areas',
      'Air-conditioning',
      'Private pool',
      'Storage room',
      'Sea view',
      'Private parking',
      'Private entrance',
      'Built-in wardrobes',
      'Garage',
    ],
    images: [
      { title: 'main-image', image: '/images/projectCard/oasis_spain.jpg' },
      { title: 'balcony', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'building-side', image: '/images/projectCard/building_side.jpg' },
      { title: 'balcony-view', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'dining-room', image: '/images/projectCard/dining_room.jpg' },
      { title: 'kitchen', image: '/images/projectCard/kitchen.jpg' },
      { title: 'living-room-view', image: '/images/projectCard/living_room_view.jpg' },
      { title: 'living-room', image: '/images/projectCard/living_room.jpg' },
      { title: 'sauna', image: '/images/projectCard/sauna.jpg' },
      { title: 'pool', image: '/images/projectCard/pool.jpg' },
      { title: 'pool-side-view', image: '/images/projectCard/pool_side_view.jpg' },
      { title: 'kitchen-back-view', image: '/images/projectCard/kitchen_back_view.jpg' },
      { title: 'outdoors-pool', image: '/images/projectCard/outdoors_pool.jpg' },
      { title: 'terrace', image: '/images/projectCard/terrace.jpg' },
      { title: 'terrace-view', image: '/images/projectCard/terrace_view.jpg' },
      { title: 'upper-terrace', image: '/images/projectCard/upper_terrace.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'full-terrace', image: '/images/projectCard/full_terrace.jpg' },
      { title: 'guest-bedroom', image: '/images/projectCard/guest_bedroom.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'master-bedroom', image: '/images/projectCard/master_bedroom.jpg' },
      { title: 'decorations', image: '/images/projectCard/decorations.jpg' },
      { title: 'kitchen-more', image: '/images/projectCard/kitchen_more.jpg' },
      { title: 'plan', image: '/images/projectCard/plan.jpg' },
    ],
  },
  {
    id: 'a2',
    image: '/images/projectCard/balcony_view.jpg',
    price: '333,000 ',
    bed: '4',
    bathrooms: '',
    pricePerMeter: '',
    title: 'some',
    location: '',
    floors: '',
    projectFloor: '2',
    rooms: '',
    type: 'Flat',
    size: '224 m2',
    description: [],
    amenities: [],
    images: [
      { title: 'main-image', image: '/images/projectCard/oasis_spain.jpg' },
      { title: 'balcony', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'building-side', image: '/images/projectCard/building_side.jpg' },
      { title: 'balcony-view', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'dining-room', image: '/images/projectCard/dining_room.jpg' },
      { title: 'kitchen', image: '/images/projectCard/kitchen.jpg' },
      { title: 'living-room-view', image: '/images/projectCard/living_room_view.jpg' },
      { title: 'living-room', image: '/images/projectCard/living_room.jpg' },
      { title: 'sauna', image: '/images/projectCard/sauna.jpg' },
      { title: 'pool', image: '/images/projectCard/pool.jpg' },
      { title: 'pool-side-view', image: '/images/projectCard/pool_side_view.jpg' },
      { title: 'kitchen-back-view', image: '/images/projectCard/kitchen_back_view.jpg' },
      { title: 'outdoors-pool', image: '/images/projectCard/outdoors_pool.jpg' },
      { title: 'terrace', image: '/images/projectCard/terrace.jpg' },
      { title: 'terrace-view', image: '/images/projectCard/terrace_view.jpg' },
      { title: 'upper-terrace', image: '/images/projectCard/upper_terrace.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'full-terrace', image: '/images/projectCard/full_terrace.jpg' },
      { title: 'guest-bedroom', image: '/images/projectCard/guest_bedroom.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'master-bedroom', image: '/images/projectCard/master_bedroom.jpg' },
      { title: 'decorations', image: '/images/projectCard/decorations.jpg' },
      { title: 'kitchen-more', image: '/images/projectCard/kitchen_more.jpg' },
      { title: 'plan', image: '/images/projectCard/plan.jpg' },
    ],
  },
  {
    id: 'a3',
    image: '/images/projectCard/apt_2.jpg',
    price: '897,000 ',
    pricePerMeter: '',
    bed: '3',
    bathrooms: '',
    title: 'Three Hill',
    location: '',
    floors: '',
    projectFloor: '2',
    rooms: '',
    type: 'Flat',
    size: '180 m2',
    description: [],
    amenities: [],
    images: [
      { title: 'main-image', image: '/images/projectCard/oasis_spain.jpg' },
      { title: 'balcony', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'building-side', image: '/images/projectCard/building_side.jpg' },
      { title: 'balcony-view', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'dining-room', image: '/images/projectCard/dining_room.jpg' },
      { title: 'kitchen', image: '/images/projectCard/kitchen.jpg' },
      { title: 'living-room-view', image: '/images/projectCard/living_room_view.jpg' },
      { title: 'living-room', image: '/images/projectCard/living_room.jpg' },
      { title: 'sauna', image: '/images/projectCard/sauna.jpg' },
      { title: 'pool', image: '/images/projectCard/pool.jpg' },
      { title: 'pool-side-view', image: '/images/projectCard/pool_side_view.jpg' },
      { title: 'kitchen-back-view', image: '/images/projectCard/kitchen_back_view.jpg' },
      { title: 'outdoors-pool', image: '/images/projectCard/outdoors_pool.jpg' },
      { title: 'terrace', image: '/images/projectCard/terrace.jpg' },
      { title: 'terrace-view', image: '/images/projectCard/terrace_view.jpg' },
      { title: 'upper-terrace', image: '/images/projectCard/upper_terrace.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'full-terrace', image: '/images/projectCard/full_terrace.jpg' },
      { title: 'guest-bedroom', image: '/images/projectCard/guest_bedroom.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'master-bedroom', image: '/images/projectCard/master_bedroom.jpg' },
      { title: 'decorations', image: '/images/projectCard/decorations.jpg' },
      { title: 'kitchen-more', image: '/images/projectCard/kitchen_more.jpg' },
      { title: 'plan', image: '/images/projectCard/plan.jpg' },
    ],
  },
];

export const projectCardItems = [
  {
    id: 'p1',
    image: '/images/projectCard/Pine_hill.jpeg',
    price: '219,000 ',
    pricePerMeter: '2638',
    bed: '2, 3',
    bathrooms: '',
    title: 'Pine Hill',
    location: 'Calle Pensamiento',
    floors: '3',
    projectFloor: '2',
    rooms: '',
    type: 'Flat',
    size: '180 m2',
    description: [],
    amenities: [],
    images: [
      { title: 'p1', image: '/images/projectCard/Pine_hill.jpeg' },
      { title: 'main-image', image: '/images/projectCard/oasis_spain.jpg' },
      { title: 'balcony', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'building-side', image: '/images/projectCard/building_side.jpg' },
      { title: 'balcony-view', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'dining-room', image: '/images/projectCard/dining_room.jpg' },
      { title: 'kitchen', image: '/images/projectCard/kitchen.jpg' },
      { title: 'living-room-view', image: '/images/projectCard/living_room_view.jpg' },
      { title: 'living-room', image: '/images/projectCard/living_room.jpg' },
      { title: 'sauna', image: '/images/projectCard/sauna.jpg' },
      { title: 'pool', image: '/images/projectCard/pool.jpg' },
      { title: 'pool-side-view', image: '/images/projectCard/pool_side_view.jpg' },
      { title: 'kitchen-back-view', image: '/images/projectCard/kitchen_back_view.jpg' },
      { title: 'outdoors-pool', image: '/images/projectCard/outdoors_pool.jpg' },
      { title: 'terrace', image: '/images/projectCard/terrace.jpg' },
      { title: 'terrace-view', image: '/images/projectCard/terrace_view.jpg' },
      { title: 'upper-terrace', image: '/images/projectCard/upper_terrace.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'full-terrace', image: '/images/projectCard/full_terrace.jpg' },
      { title: 'guest-bedroom', image: '/images/projectCard/guest_bedroom.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'master-bedroom', image: '/images/projectCard/master_bedroom.jpg' },
      { title: 'decorations', image: '/images/projectCard/decorations.jpg' },
      { title: 'kitchen-more', image: '/images/projectCard/kitchen_more.jpg' },
      { title: 'plan', image: '/images/projectCard/plan.jpg' },
    ],
  },
  {
    id: 'p2',
    image: '/images/projectCard/laguna.jpeg',
    price: '215,000',
    pricePerMeter: '1514',
    bed: '3',
    bathrooms: '',
    title: 'Laguna Residence',
    location: 'Mijas, Spain',
    floors: '4',
    projectFloor: '2',
    rooms: '',
    type: 'Flat',
    size: '180 m2',
    description: [],
    amenities: [],
    images: [
      { title: 'p2', image: '/images/projectCard/laguna.jpeg' },
      { title: 'main-image', image: '/images/projectCard/oasis_spain.jpg' },
      { title: 'balcony', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'building-side', image: '/images/projectCard/building_side.jpg' },
      { title: 'balcony-view', image: '/images/projectCard/balcony_view.jpg' },
      { title: 'dining-room', image: '/images/projectCard/dining_room.jpg' },
      { title: 'kitchen', image: '/images/projectCard/kitchen.jpg' },
      { title: 'living-room-view', image: '/images/projectCard/living_room_view.jpg' },
      { title: 'living-room', image: '/images/projectCard/living_room.jpg' },
      { title: 'sauna', image: '/images/projectCard/sauna.jpg' },
      { title: 'pool', image: '/images/projectCard/pool.jpg' },
      { title: 'pool-side-view', image: '/images/projectCard/pool_side_view.jpg' },
      { title: 'kitchen-back-view', image: '/images/projectCard/kitchen_back_view.jpg' },
      { title: 'outdoors-pool', image: '/images/projectCard/outdoors_pool.jpg' },
      { title: 'terrace', image: '/images/projectCard/terrace.jpg' },
      { title: 'terrace-view', image: '/images/projectCard/terrace_view.jpg' },
      { title: 'upper-terrace', image: '/images/projectCard/upper_terrace.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'full-terrace', image: '/images/projectCard/full_terrace.jpg' },
      { title: 'guest-bedroom', image: '/images/projectCard/guest_bedroom.jpg' },
      { title: 'shower', image: '/images/projectCard/shower.jpg' },
      { title: 'master-bedroom', image: '/images/projectCard/master_bedroom.jpg' },
      { title: 'decorations', image: '/images/projectCard/decorations.jpg' },
      { title: 'kitchen-more', image: '/images/projectCard/kitchen_more.jpg' },
      { title: 'plan', image: '/images/projectCard/plan.jpg' },
    ],
  },
  {
    id: 'p3',
    image: '/images/projectCard/baviera_golf.jpeg',
    price: '897,000',
    pricePerMeter: '1719',
    bed: '2, 3',
    bathrooms: '',
    title: 'Baviera Golf',
    location: 'Caleta de Valez, Spain',
    floors: '3',
    projectFloor: '2',
    rooms: '',
    type: 'Flat',
    size: '180 m2',
    description: [],
    amenities: [],
    images: [{ title: 'p3', image: '/images/projectCard/baviera_golf.jpeg' }],
  },
  {
    id: 'p4',
    image: '/images/projectCard/insur_scala.jpeg',
    price: '210,000',
    pricePerMeter: '1066',
    bed: '1,2,3',
    bathrooms: '',
    title: 'Insur Scala',
    location: 'Estepona, Spain',
    floors: '1',
    projectFloor: '2',
    rooms: '',
    type: 'Flat',
    size: '180 m2',
    description: [],
    amenities: [],
    images: [{ title: 'p4', image: '/images/projectCard/insur_scala.jpeg' }],
  },
  {
    id: 'p5',
    image: '/images/projectCard/cala_swing.jpeg',
    price: '222,000',
    pricePerMeter: '2000',
    bed: '1,2,3',
    bathrooms: '',
    title: 'Cala Swing',
    location: 'Avenida Puerto de los Gatos de Cortijo Colorado',
    floors: '4',
    projectFloor: '2',
    rooms: '',
    type: 'Flat',
    size: '180 m2',
    description: [],
    amenities: [],
    images: [{ title: 'p5', image: '/images/projectCard/cala_swing.jpeg' }],
  },
];
