//section 1 Hero
export const mainHeroSwiperData = [
  { id: 1, name: 'name', src: '/main/section1hero/slide1.jpg' },
  { id: 2, name: 'name', src: '/main/section1hero/slide2.jpg' },
  { id: 3, name: 'name', src: '/main/section1hero/slide3.jpeg' },
];

//section 2 Top Project Test
export const mainTopProjectsSwiperData = [
  { id: 1, title: 'Salvia', area: 'San Pedro Alcantara', src: '/main/forTest/img1.png' },
  { id: 2, title: 'Atalaya Emotion', area: 'Estepona', src: '/main/forTest/img2.png' },
  { id: 3, title: 'Salvia', area: 'San Pedro Alcantara', src: '/main/forTest/img3.png' },
  { id: 4, title: 'Atalaya Emotion', area: 'Estepona', src: '/main/forTest/img1.png' },
  { id: 5, title: 'Salvia', area: 'San Pedro Alcantara', src: '/main/forTest/img2.png' },
  { id: 6, title: 'Atalaya Emotion', area: 'Estepona', src: '/main/forTest/img3.png' },
  { id: 7, title: 'Salvia', area: 'San Pedro Alcantara', src: '/main/forTest/img1.png' },
  { id: 8, title: 'Atalaya Emotion', area: 'Estepona', src: '/main/forTest/img2.png' },
];

//section 3 MainSwiperSectionData
export const mainSwiperSectionData = [
  {
    id: 1,
    title: 'Estepona',
    description:
      'Nestled along the sun-kissed shores of the Costa del Sol, Malaga is a captivating city that effortlessly blends rich history.',
    price: '2.3M',
    bestFor: 'investment',
    airport: '55',
    area: 'San Pedro Alcantara',
    src: '/main/section2topProjectTest/atalaya.png',
  },
  {
    id: 2,
    title: 'Atalaya Emotion',
    description: 'Known for its captivating old town, stunning beaches, and vibrant cultural scene.',
    price: '1.2M',
    bestFor: 'investment',
    airport: '20',
    area: 'Estepona',
    src: '/main/section2topProjectTest/salvia.png.jpg',
  },
  {
    id: 3,
    title: 'Salvia',
    description:
      'Known for its captivating old town, stunning beaches, and vibrant cultural scene, Estepona has become an increasingly popular destination for both tourists and expatriates',
    price: '2.3M',
    bestFor: 'living',
    airport: '55',
    area: 'San Pedro Alcantara',
    src: '/main/section2topProjectTest/atalaya.png',
  },
  {
    id: 4,
    title: 'Atalaya Emotion',
    description: 'Known for its captivating old town, stunning beaches, and vibrant cultural scene.',
    price: '1.2M',
    bestFor: 'investment',
    airport: '20',
    area: 'Estepona',
    src: '/main/section2topProjectTest/salvia.png',
  },
  {
    id: 5,
    title: 'Salvia',
    description:
      'Known for its captivating old town, stunning beaches, and vibrant cultural scene, Estepona has become an increasingly popular destination for both tourists and expatriates',
    price: '2.3M',
    bestFor: 'living',
    airport: '55',
    area: 'San Pedro Alcantara',
    src: '/main/section2topProjectTest/atalaya.png',
  },
  {
    id: 6,
    title: 'Atalaya Emotion',
    description: 'Known for its captivating old town, stunning beaches, and vibrant cultural scene.',
    price: '1.2M',
    bestFor: 'investment',
    airport: '20',
    area: 'Estepona',
    src: '/main/section2topProjectTest/salvia.png',
  },
];
export const selectedSwiperSectionData = [
  {
    id: 1,
    name: 'Salvia',
    area: 'San Pedro Alcantara',
    price: '761,500',
    bed: '2,3,4 bed',
    value: '3500 m2',
    floors: '4',
    src: '/main/forTest/img3.png',
  },
  {
    id: 2,
    name: 'Capri',
    area: 'Estepona, Spain',
    price: '348,000',
    bed: '2,3,4 bed',
    value: '2560 m2',
    floors: '4',
    src: '/main/forTest/img2.png',
  },
  {
    id: 3,
    name: 'Atico Rio Real',
    area: 'Marbella, Spain',
    price: '2,900,000',
    bed: '2,3,4 bed',
    value: '5465 m2',
    floors: '4',
    src: '/main/forTest/img1.png',
  },
  {
    id: 4,
    name: 'Salvia',
    area: 'San Pedro Alcantara',
    price: '761,500',
    bed: '2,3,4 bed',
    value: '3500 m2',
    floors: '4',
    src: '/main/forTest/img3.png',
  },
  {
    id: 5,
    name: 'Capri',
    area: 'Estepona, Spain',
    price: '348,000',
    bed: '2,3,4 bed',
    value: '2560 m2',
    floors: '4',
    src: '/main/forTest/img2.png',
  },
  {
    id: 6,
    name: 'Atico Rio Real',
    area: 'Marbella, Spain',
    price: '2,900,000',
    bed: '2,3,4 bed',
    value: '5465 m2',
    floors: '4',
    src: '/main/forTest/img1.png',
  },
  {
    id: 7,
    name: 'Salvia',
    area: 'San Pedro Alcantara',
    price: '761,500',
    bed: '2,3,4 bed',
    value: '3500 m2',
    floors: '4',
    src: '/main/forTest/img3.png',
  },
  {
    id: 8,
    name: 'Capri',
    area: 'Estepona, Spain',
    price: '348,000',
    bed: '2,3,4 bed',
    value: '2560 m2',
    floors: '4',
    src: '/main/forTest/img2.png',
  },
  {
    id: 9,
    name: 'Atico Rio Real',
    area: 'Marbella, Spain',
    price: '2,900,000',
    bed: '2,3,4 bed',
    value: '5465 m2',
    floors: '4',
    src: '/main/forTest/img1.png',
  },
  {
    id: 10,
    name: 'Salvia',
    area: 'San Pedro Alcantara',
    price: '761,500',
    bed: '2,3,4 bed',
    value: '3500 m2',
    floors: '4',
    src: '/main/forTest/img3.png',
  },
  {
    id: 11,
    name: 'Capri',
    area: 'Estepona, Spain',
    price: '348,000',
    bed: '2,3,4 bed',
    value: '2560 m2',
    floors: '4',
    src: '/main/forTest/img2.png',
  },
  {
    id: 12,
    name: 'Atico Rio Real',
    area: 'Marbella, Spain',
    price: '2,900,000',
    bed: '2,3,4 bed',
    value: '5465 m2',
    floors: '4',
    src: '/main/forTest/img1.png'
  },
];
